### ISSUE TITLE
[SUGGESTION] Add Vine tip (edited)

### ISSUE THREAD

**Issue by MarkinhosMLP** [HibiscusMC/HMCLeaves#13]
Just like vanilla twisting/cave/weeping vines, they have a tip
which is at the end of the block

for example 
/setblock twisting_vines_plant = normal vine
/setblock twisting_vines = vine tip

```
twisting-vines:
  custom_vine:
    name: "&6Custom Vine"
    state-id: 1
    vine-tip-id: 2
```
