### ISSUE TITLE
[SUGGESTION] Custom-Berry Item

### ISSUE THREAD

**Issue by MarkinhosMLP** [HibiscusMC/HMCLeaves#19]
custom berries items for cave vines
could be even an oraxen item

```yml
cave-vines:
  test_cave_vine:
    material: paper
    with-glow-berry-id: test_cave_vine_berries
    model-data: 5
    name: "&6Test Cave Vine"
    lore:
      - "&aLine 1"
    state-id: 2
    tipped-state-id: 3
    should-grow-berries: true
    berry-material: PAPER // oraxen:custom_berry
    berry-model-data: 6
    berry-name:  "&6Test Berry"
    berry-lore:
      - "&aLine 1"
```
