### ISSUE TITLE
[BUG] Leaves not fully working

### ISSUE THREAD

**Issue by MarkinhosMLP** [HibiscusMC/HMCLeaves#25]
worth mentioning:

config > `only-follow-world-persistence-if-connected-to-log: true`
item:
```yml
leaves:
  palm_leaves:
    leaf-material: OAK_LEAVES
    state-id: 1
    sapling: palm_saplings
    leaf-drop-replacement: palm_leaves_persistent
```

https://github.com/HibiscusMC/HMCLeaves/assets/47507632/37ebb749-6177-42e7-97a4-fc69b329f95f

I created the schematic and used the convert command
