### ISSUE TITLE
[BUG/SUGGESTION] Non-Strippable wood

### ISSUE THREAD

**Issue by MarkinhosMLP** [HibiscusMC/HMCLeaves#28]
at the moment, you need to specify a stripped version of the log, otherwise, using the reload command will not work and it wont update
the thing is, im making the palm crown to work like a wood, so the leaves connected to it will make them not fall, till you break it

at the moment i made it like this
```yml
  palm_crown:
    log-material: DARK_OAK_WOOD
    stripped-log-material: DARK_OAK_WOOD #does not work if i remove it
    stripped-log-id: palm_crown #does not work if i remove it
```

but you can strip it infinetly, or even.. just make it into stripped version of the log material (stripped dark oak wood, in my case)

also, this will be useful cause at the moment seems like it is overwriting oraxen strippable blocks
