### ISSUE TITLE
Plugin configuration

### ISSUE THREAD

**Issue by matyasvane** [HibiscusMC/HMCLeaves#3]
Hey,
In the configuration of the plugin, the user defines the name of the item, which can then be given via HMCLeaves. The problem is that there is no naming option, so the name is chosen as the name.

```
  "wisteria_leaves": <===
    leaf-material: OAK_LEAVES
    material: PAPER
    model-data: 1 # If using Oraxen/IA, you can ignore this option. Get the leaf item from /o inv or /ia.
    # Blockstate Data
    distance: 1
    persistent: true
    # Will this leaf decay, or will it be persistent?
    actually-persistent: false
    # The item that replaces the normal sapling drop. For example if you have an item that is textured to look like a sapling that matches the tree this leaf goes with
    sapling:
      hook-id: test-sapling
      material: OAK_SAPLING
      amount: 1
      name: "&aTest"
      model-data: 1
      lore:
        - "&7This is a test"
        - "&7This is a test"
```
It then looks like this in the game:
![image](https://user-images.githubusercontent.com/75536352/202972206-cb0b1974-3d28-4ed1-b0a0-f30ba437e9c4.png)

**-------------------**

Next is _model-data_:

model-data: 1 # If using Oraxen/IA, you can ignore this option. Get the leaf item from /o inv or /ia.

But I'm not sure about the correct syntax when using itemsadder.

**-------------------**

Next, there no way to define the color of the object using rgb? For example, I have an item that is white, but when I place it, it turns green.

Inventory:
![image](https://user-images.githubusercontent.com/75536352/202972891-8d8230de-7a42-4683-b23a-29b038559967.png)

Game:
![image](https://user-images.githubusercontent.com/75536352/202972932-539e4b4b-1f8c-488a-90ac-5053938ebecc.png)

**-------------------**

Last, it is possible to add logs in the configuration, but here you need to enter a precisely defined name from the noteblock, you can't do the same as with leaves when I use ItemsAdder or some kind of hook.
